### ISSUE TITLE
What might be causing this?

### ISSUE THREAD

**Issue by Redcom1988** [TheGoogolMoon/PHMTMod#1]
[19:06:27] [28/WARN] [tML]: Silently Caught Exception: 
System.ArgumentOutOfRangeException: minValue must be less than maxValue
Parameter name: minValue
   at Terraria.Utilities.UnifiedRandom.Next(Int32 minValue, Int32 maxValue)
   at PreHMTeleportation.PHMTWorld.PHMTSpaceShip(GenerationProgress progress) in PreHMTeleportation\PHMTWorld.cs:line 47
   at Terraria.GameContent.Generation.PassLegacy.Apply(GenerationProgress progress)
   at Terraria.World.Generation.WorldGenerator.GenerateWorld(GenerationProgress progress)
   at Terraria.WorldGen.generateWorld(Int32 seed, GenerationProgress customProgressObject)
   at Terraria.WorldGen.do_worldGenCallBack(Object threadContext)
   at Terraria.WorldGen.worldGenCallBack(Object threadContext)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

[19:06:27] [28/ERROR] [tML]: A problem was encountered during world generation
PHMT Mod Spaceship
System.ArgumentOutOfRangeException: minValue must be less than maxValue
Parameter name: minValue
   at Terraria.Utilities.UnifiedRandom.Next(Int32 minValue, Int32 maxValue)
   at PreHMTeleportation.PHMTWorld.PHMTSpaceShip(GenerationProgress progress) in PreHMTeleportation\PHMTWorld.cs:line 46
   at Terraria.GameContent.Generation.PassLegacy.Apply(GenerationProgress progress)
   at Terraria.World.Generation.WorldGenerator.GenerateWorld(GenerationProgress progress)
[19:06:27] [28/ERROR] [Terraria]: A problem was encountered during world generation
System.ArgumentOutOfRangeException: minValue must be less than maxValue
Parameter name: minValue
   at Terraria.World.Generation.WorldGenerator.GenerateWorld(GenerationProgress progress)
   at Terraria.WorldGen.generateWorld(Int32 seed, GenerationProgress customProgressObject)
   at Terraria.WorldGen.do_worldGenCallBack(Object threadContext)
   at Terraria.WorldGen.worldGenCallBack(Object threadContext)

**Comment by Redcom1988** [comment]
It's not any incompatibilty issue, I've tried only using the PHMT mod and it still does it

This issue only comes up in world generation

**Comment by TheGoogolMoon** [comment]
Ah, that's what I get for coding at 4AM, I'd written "low" and "high" in the wrong order. I fixed it now. Thank you for bringing it to my attention!
